environment_file: "$(find smarc_stonefish_worlds)/data/kristineberg/kristineberg_env.scn"
# map ref is located at the start of the bridge (left side corner) over to the sauna
latitude: "58.249721"
longitude: "11.44624"
algae_texture_dir: "$(find smarc_stonefish_worlds)/data/algae/textures"